name: 'Jira Check'
on:
  pull_request:
    types: [assigned, opened, reopened]

jobs:
  check-jira-title:
    runs-on: ubuntu-latest
    steps:
      - uses: morrisoncole/pr-lint-action@v1.1.1
        with:
          title-regex: '^((CORDA|EG|ENT|INFRA)-\d+|NOTICK)(.*)'
          on-failed-regex-comment: # default is PR title failed to match %regex%.