name: 'Jira Check'
on:
  pull_request:
    types:
      # Check title when opened.
      - opened
      # Check title when new commits are pushed.
      # Required to use as a status check.
      - synchronize

jobs:
  check-jira-title:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: schife/check-pull-request-title@v1
        with:
          pattern: '^((CORDA|EG|ENT|INFRA)-\d+|NOTICK)(.*)'
